# Base images for deployment, with needed dependencies.
# This image is created to avoid installing the dependencies each time.
FROM python:3.8-alpine

# Install dependencies for the cryptography package.
RUN apk add --no-cache \
        gcc \
        musl-dev \
        python3-dev \
        libffi-dev \
        openssl-dev

# Copy the requirements and install them.
COPY requirements.txt .
RUN pip install -r requirements.txt
