{
 "title": "Livetracking by channel",
 "time": { "from": "now-5m", "to": "now" },
 "templating": {
  "list": [
   { "name": "livetrack", "query": { "query": "label_values(livetrack)" } }
  ]
 },
 "panels": [
  {
   "title": "Requests rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "rate(livetrack_requests_total{livetrack=\"$livetrack\"}[5m])",
     "legendFormat": "{{livetrack}}"
    }
   ]
  },
  {
   "title": "Pilots currently flying",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "livetrack_pilots_flying{livetrack=\"$livetrack\"}",
     "legendFormat": "{{livetrack}}"
    }
   ]
  },
  {
   "title": "Number of messages sent",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "livetrack_messages_send_total{livetrack=\"$livetrack\"}",
     "legendFormat": "{{livetrack}}"
    }
   ]
  },
  {
   "title": "Number of errors",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "expr": "livetrack_errors_total{livetrack=\"$livetrack\"}",
     "legendFormat": "{{livetrack}}"
    }
   ]
  }
 ]
}