{
 "title": "Livetracking all",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Requests rate",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "rate(livetrack_requests_total[5m])",
     "legendFormat": "{{livetrack}}"
    }
   ]
  },
  {
   "title": "Pilots currently flying",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "livetrack_pilots_flying", "legendFormat": "{{livetrack}}" }
   ]
  },
  {
   "title": "Number of errors",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    { "expr": "livetrack_errors_total", "legendFormat": "{{livetrack}}" }
   ]
  },
  {
   "title": "Number of messages sent",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "targets": [
    { "expr": "livetrack_messages_send_total", "legendFormat": "{{livetrack}}" }
   ]
  }
 ]
}